//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingDropdowns {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm rsvpform;
		
		protected System.Web.UI.HtmlControls.HtmlInputText Name;
		
		protected System.Web.UI.HtmlControls.HtmlInputText Email;
		
		protected System.Web.UI.HtmlControls.HtmlInputText Phone;
		
		protected System.Web.UI.HtmlControls.HtmlSelect WillAttend;
	}
}
